# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28de04d55c981cc052070a50a50403cb9b098754cb8cfdce07da95654373cdbc7bab0fb5c48d0412aefe6b98268b3a9697b3bab9ac8c7d6fd41805c2ad0d2834

test:
  secret_key_base: 2c88f95064c84801ceba4d097a5ce94d13be237913935ebc703345344baa211a2e894cd6f148a174529472d2fc0549e4d2285e6c39f5133b3863a00cb87bec44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
